name: CI

on:
  push:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
      run: |
        git switch master
        touch test.txt
        git add .
        git config user.name "bab2683"
        git config user.email "barahona.braulio@gmail.com"
        git commit -m "test commit"
        git config --get-all http.https://github.com/bab2683/bab.extraheader
        git config --get-all http.proxy
        node ./scripts/test.js
