name: Push on master

on:
  push:
    branches:
    - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: commit message
      run: |


    - name: Deploy
      run: |
        MESSAGE=git show --oneline -s HEAD
        KEYWORD='skip-ci'
        if [ ["$MESSAGE" == *"$KEYWORD"] ]
        then
          echo Changes are not being deployed
        else
          # deploy logic here
          echo Changes deployed
        fi
