name: Push on master

on:
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name : Check env
      run: node ./scripts/test.js

    # - name: Install environment
    #   if: contains(github.event.commits[0].message, '[skip-ci]') == false
    #   run: npm install
    # - name: Set Npm Config
    #   if: contains(github.event.commits[0].message, '[skip-ci]') == false
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    #   run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
    # - name: Deploy
    #   if: contains(github.event.commits[0].message, '[skip-ci]') == false
    #   run: npm run lib-publish
