name: Push on master

on:
  push:
    branches:
    - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      if: contains(github.event.commits[0].message, '[skip-ci]') == false
      run: echo Deploy logic here
