name: Merge on master

on:
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        if: github.event.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install environment
        if: github.event.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: npm install
      - name: Set Npm Config
        if: github.event.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
      - name: Deploy
        if: github.event.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        env:
          CI: true
        run: npm run lib-publish
