name: Push on master

on:
  push:
    branches:
    - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Deploy
      run: |
        if [contains(github.event.commits[0].message, '[skip-ci]') == false]; then
          echo Deployed here
        fi
