name: PR on master

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Linter
        run: lint-staged
      - name: Tests coverage
        run: npm run test:cov


